services:
  userservice:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - wishly_network

  wishlistservice:
    build:
      context: ./WishlistService
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - wishly_network

networks:
  wishly_network:
    driver: bridge
